Repository NotKyoyo/random-anime-quotes, pull requests merged in 2022-10, with the labels that each got.

#5 Bug fixes and Readme updated
  README.md
  package-lock.json
  package.json
Labels: enhancement, hacktoberfest-accepted

#6 feature: added linter
  .eslintrc.js
  README.md
  index.js
  package-lock.json
  package.json
Labels: enhancement, hacktoberfest-accepted

#7 Updated documentation in README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#8 Staging
  .eslintrc.js
  .github/FUNDING.yml
  README.md
  index.js
  package-lock.json
  package.json
Labels: hacktoberfest-accepted
